### ISSUE TITLE
[Windows 10] Unable to locate turbojpeg library automatically

### ISSUE THREAD

**Issue by riven314** [lilohuang/PyTurboJPEG#17]
I am installing the package in Windows. Following the [instruction](https://pypi.org/project/PyTurboJPEG/?fbclid=IwAR2tbXI5kvr7juvm63JazeHZpSXkn5gaRXFzSz5Z_gfqD20GS-fn9F9KSIk), I did the following two steps:
1. Installed the latest version of libjpeg-turbo (i.e. ```libjpeg-turbo-2.0.3-gcc.exe```). After the installation, I saw it is installed in ```C:/libjpeg-turbo-gcc```.
2. execute ```$ pip install -U git+git://github.com/lilohuang/PyTurboJPEG.git```

After the above installation steps, I encountered the following error when running the sample script:
```
>>> from turbojpeg import TurboJPEG
>>> x = TurboJPEG()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\u3509\Anaconda3\envs\realsense\lib\site-packages\turbojpeg.py", line 97, in __init__
    self.__find_turbojpeg() if lib_path is None else lib_path)
  File "C:\Users\u3509\Anaconda3\envs\realsense\lib\site-packages\turbojpeg.py", line 257, in __find_turbojpeg
    'Unable to locate turbojpeg library automatically. '
RuntimeError: Unable to locate turbojpeg library automatically. You may specify the turbojpeg library path manually.
e.g. jpeg = TurboJPEG(lib_path)
```

I noticed I may need to specify library path explicitly, but I can't find the target files (i.e. ```turbojpeg.dll```, ```libturbojpeg.so```, or ```libturbojpeg.so```) in my libjpeg-turbo directory (i.e. ```C:/libjpeg-turbo-gcc```)
Below is what I saw from ```C:\libjpeg-turbo-gcc\lib\  ```
```
(base) PS C:\Users\u3509> ls C:\libjpeg-turbo-gcc\lib\                                                                  

    Directory: C:\libjpeg-turbo-gcc\lib


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/20/2019   8:55 PM                pkgconfig
-a----         9/5/2019   7:38 AM         772182 libjpeg.a
-a----         9/5/2019   7:35 AM          70746 libjpeg.dll.a
-a----         9/5/2019   7:36 AM         878050 libturbojpeg.a
-a----         9/5/2019   7:37 AM          52760 libturbojpeg.dll.a
```

**Comment by lilohuang** [comment]
Could you uninstall your previous libjpeg-turbo-2.0.3-gcc.exe installation, and installing libjpeg-turbo-2.0.3-vc64.exe? Please let me know if it doesn't work.

Currently, the PyTurboJPEG should only support locating library automatically from VC64 version, I will keep improving it even for GCC version.

**Comment by lilohuang** [comment]
I guess the libjpeg-turbo-2.0.3-gcc.exe pre-built binary may have bug. Could you uninstall your previous libjpeg-turbo-2.0.3-gcc.exe installation, and installing libjpeg-turbo-2.0.3-vc64.exe? I expect you should see the turbojpeg.dll under C:/libjpeg-turbo64/bin/ directory.

Please let me know if it doesn't work for you. Thank you.

![image](https://user-images.githubusercontent.com/8341304/67161882-5e55ce80-f391-11e9-8e2a-b7b1b203dc38.png)

**Comment by riven314** [comment]
@lilohuang , Thanks!
I uninstalled libjpeg-turbo-2.0.3-gcc.exe and then installed libjpeg-turbo-2.0.3-vc64.exe. It solves the issue.

**Comment by neoglez** [comment]
Just as info: the same happened to me with version 3.x. Installing under Windows 10 x64 with `-gcc.exe` did not work. Using the installer `-vc64.exe` worked like a charm.
