### ISSUE TITLE
Cropped image is getting distorted

### ISSUE THREAD

**Issue by srijiths** [lilohuang/PyTurboJPEG#2]
Hi,

I have cropped an image part from an open cv frame. Then i encode it , decode it and write it as a file gives a distorted image.

```
Encoding
---------
face_crop = frame[bbox[1]:bbox[3], bbox[0]:bbox[2], :]
jpg_as_text = turbo.encode(face_crop)
Decoding
------------
img_file = io.BytesIO(jpg_as_text)
face_crop_decoded = turbo.decode(img_file.read())
```

Now if i write face_crop_decoded using cv2.imwrite('face.jpg', face_crop_decoded) , distorted lines are coming , not the actual face.

But if i use original face_crop for cv2.imwrite , proper face is getting written. So encode-decode-write causing some issues. But the frame variable which is used in the first line is actually encoded-decoded, there i am able to encode and decode properly. But on face_crop encode-decode is not working. What would be the issue here ?

Thank You

**Comment by lilohuang** [comment]
I should be able to fix it within two days. Please stay tuned.

**Comment by srijiths** [comment]
Cool !! Thank You @lilohuang By the way i should tell you that your solution made it possible to encode 2850 frames in 40 secs. With cv2.imencode it was taking 3.3 mins. Super fast !! :)

**Comment by lilohuang** [comment]
@srijiths  Please give a try with the new version (1.1.3), and let me know if the bug is still there.
e.g. pip install -U git+git://github.com/lilohuang/PyTurboJPEG.git

**Comment by srijiths** [comment]
@lilohuang Thank You..Its working.. :)
