### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found.

### ISSUE THREAD

**Issue by jxylon** [lilohuang/PyTurboJPEG#20]
Traceback (most recent call last):
  File "D:/pythonproj/school/dipclass/dipex4.py", line 202, in <module>
    homework1()
  File "D:/pythonproj/school/dipclass/dipex4.py", line 184, in homework1
    jpeg = TurboJPEG('E:/libjpeg-turbo-gcc/')

**Comment by lilohuang** [comment]
jpeg = TurboJPEG('E:/libjpeg-turbo-gcc/') should be changed to jpeg = TurboJPEG('E:/libjpeg-turbo-gcc/bin/turbojpeg.dll')

If E:/libjpeg-turbo-gcc/bin/turbojpeg.dll file is missing, you may download the TurboJPEG (libjpeg-turbo-2.0.3-vc64.exe) from https://sourceforge.net/projects/libjpeg-turbo/files/2.0.3/, and reinstall it.
