### ISSUE TITLE
PyTurboJPEG not working with latest (2.0.4) release of libturbo-jpeg

### ISSUE THREAD

**Issue by trdastidar** [lilohuang/PyTurboJPEG#21]
The error that I get is:
```
/opt/libjpeg-turbo/lib64/libjpeg.so: undefined symbol: tjInitDecompress
```
How to reproduce:
Download the .deb for 2.0.4 from https://sourceforge.net/projects/libjpeg-turbo/ and install using dpkg
Then, from python
```
>>> from turbojpeg import TurboJPEG, TJPF_GRAY, TJSAMP_GRAY
>>> jpeg = TurboJPEG("/opt/libjpeg-turbo/lib64/libjpeg.so")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/test/.local/lib/python2.7/site-packages/turbojpeg.py", line 98, in __init__
    self.__init_decompress = turbo_jpeg.tjInitDecompress
  File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /opt/libjpeg-turbo/lib64/libjpeg.so: undefined symbol: tjInitDecompress

```
I checked and indeed the symbol tjInitDecompress isn't defined in the new .so file.

Version 2.0.3 didn't have this problem (the symbol is defined in the .so for 2.0.3)

**Comment by lilohuang** [comment]
You need to load **libturbojpeg.so** rather than **libjpeg.so**, I also verified PyTurboJPEG with .deb 2.0.4, it works well. Please let me know if you still have issue on this. Thank you.

`jpeg = TurboJPEG("/opt/libjpeg-turbo/lib64/libturbojpeg.so")`

**Comment by trdastidar** [comment]
Sorry for the non-issue :-)
