### ISSUE TITLE
'Unable to locate turbojpeg library automatically. '             'You may specify the turbojpeg library path manually.\n'             'e.g. jpeg = TurboJPEG(lib_path)'

### ISSUE THREAD

**Issue by kitcatkai** [lilohuang/PyTurboJPEG#27]
I `pip3 install PyTurboJPEG`. When I run an open-source `openpose` code, I encounter this issue. Anyone facing this similar issue?

**Comment by lilohuang** [comment]
Did you see [README](https://github.com/lilohuang/PyTurboJPEG/blob/master/README.md) file and follow the **Installation** guideline to install libjpeg-turbo on your machine?

## Installation

### macOS
- brew install jpeg-turbo
- pip install -U git+git://github.com/lilohuang/PyTurboJPEG.git

### Windows 
- Download [libjpeg-turbo official installer](https://sourceforge.net/projects/libjpeg-turbo/files) 
- pip install -U git+git://github.com/lilohuang/PyTurboJPEG.git

### Linux
- Download [libjpeg-turbo.repo](https://libjpeg-turbo.org/pmwiki/uploads/Downloads/libjpeg-turbo.repo) to /etc/yum.repos.d/
- sudo yum install libjpeg-turbo-official
- pip install -U git+git://github.com/lilohuang/PyTurboJPEG.git

**Comment by kitcatkai** [comment]
Hi lilohuang,

I am having difficulty installing using your linux instruction as my Ubuntu 18.04 does not come with `yum` package installer. I only have `apt-get`. Thanks for helping out, I am new to this way of installation.

**Comment by lilohuang** [comment]
Try to run the below commands, I just verified it on my Ubuntu 18.04. Good luck

sudo apt-get update -y
sudo apt-get install -y libturbojpeg

**Comment by lilohuang** [comment]
@kitcatkai 

Try to run the below commands, I verified it on my Ubuntu 18.04. Please close ticket if it works for you. Thank you!

```
sudo apt-get update -y
sudo apt-get install -y libturbojpeg
```

**Comment by lilohuang** [comment]
Since there is no response, I'm going to close this issue. Please open it again If my answer doesn't work for you. Thanks.

**Comment by kitcatkai** [comment]
Yes it works. Replied so anyone encountering the same issue can just follow ^ instruction. Thanks @lilohuang

**Comment by Ashwin-Ramesh2607** [comment]
@lilohuang I am getting this error message when I run `sudo apt-get install -y libturbojpeg`

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libturbojpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libturbojpeg0

E: Package 'libturbojpeg' has no installation candidate
```

**Comment by lilohuang** [comment]
@Ashwin-Ramesh2607 

I don't know what's your OS version, and here I provided another approach for your reference,

`wget https://netix.dl.sourceforge.net/project/libjpeg-turbo/2.0.5/libjpeg-turbo-official_2.0.5_amd64.deb`
`sudo dpkg -i libjpeg-turbo-official_2.0.5_amd64.deb`

This will install the libjpeg-turbo-official library to /opt/libjpeg-turbo/lib64
Once it's done, you should be able to use PyTurboJPEG w/o specifying the library path.

Good luck!

**Comment by Ashwin-Ramesh2607** [comment]
@lilohuang Thanks for the approach. However, I solved it using a slightly different command `sudo apt-get install -y libturbojpeg-dev`

**Comment by agasthyahd** [comment]
what about for windows installation

**Comment by lilohuang** [comment]
> what about for windows installation

@agasthyahd Have you seen the [README](https://github.com/lilohuang/PyTurboJPEG/blob/master/README.md) file and followed the installation guidelines to install libjpeg-turbo on your Windows machine? It is recommended to download the official libjpeg-turbo installer (e.g., vc64.exe or gcc64.exe) and install it using the default settings. Once this is done, PyTurboJPEG should be able to load it properly.

<img width="1017" alt="image" src="https://github.com/lilohuang/PyTurboJPEG/assets/8341304/30da9b03-c9c4-4758-974d-614b8027799b">
