### ISSUE TITLE
Cannot install due to timeout

### ISSUE THREAD

**Issue by chenzhutian** [lilohuang/PyTurboJPEG#29]
![image](https://user-images.githubusercontent.com/3315274/85917349-f3e41f00-b88b-11ea-8a59-e3dbd6b2dcb9.png)

Could you please help?

**Comment by lilohuang** [comment]
@chenzhutian I just tried to install PyTurboJPEG, and didn't see the connection timed out issue. I guess your network connection might be blocked by firewall or something like that.

An alternative solution is to download https://github.com/lilohuang/PyTurboJPEG/archive/master.zip manually and then install it with pip command. Good luck!

e.g.
```
wget https://github.com/lilohuang/PyTurboJPEG/archive/master.zip
pip install master.zip -U
```

**Comment by chenzhutian** [comment]
fixed. I used https instead of git.
Thank you very much
