### ISSUE TITLE
Lossless drop

### ISSUE THREAD

**Issue by tomazz75** [lilohuang/PyTurboJPEG#37]
Hi,

any chance you could add lossless drop?

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/transupp.h

 * A lossless drop option is also provided, which allows another JPEG image to
 * be inserted ("dropped") into the source image data at a given position,
 * replacing the existing image data at that position.  Both the source image
 * and the drop image must have the same subsampling level.  It is best if they
 * also have the same quantization (quality.)  Otherwise, the quantization of
 * the output image will be adapted to accommodate the higher of the source
 * image quality and the drop image quality.  The trim option can be used with
 * the drop option to requantize the drop image to match the source image.

thank you,
Tomaz

**Comment by lilohuang** [comment]
Hi Tomaz,

Thanks for raising this topic. The PyTurboJPEG is a Python wrapper of libjpeg-turbo ([TurboJPEG API](https://cdn.rawgit.com/libjpeg-turbo/libjpeg-turbo/master/doc/html/group___turbo_j_p_e_g.html)). Unfortunately, the lossless drop is not covered by TurboJPEG API at this moment, I will keep monitoring libjpeg-turbo release and trying to support the lossless drop when it's available in TurboJPEG API. Sorry about that.

Thanks,
Lilo
