### ISSUE TITLE
lose rotation info using this repo

### ISSUE THREAD

**Issue by lfxx** [lilohuang/PyTurboJPEG#38]
Now,i have a picture at 
![cong](https://user-images.githubusercontent.com/27956643/122202251-7025a700-cecf-11eb-8f3c-f1f43a7f254f.jpg)

when i use 
```
img = cv2.imread("cong.jpg")
```
the picture is been correctly displayed.But when i use
```
in_file = open("cong.jpg", 'rb')
img = jpeg.decode(in_file.read())
in_file.close()
```
the picture loses its rotation info which leads to wrong display.
You can try and hope that you can fix this bug.

**Comment by lilohuang** [comment]
In fact, the PyTurboJPEG (TurboJPEG API of libjpeg-turbo) does the decoding work perfectly to return the actual image (unrotated image) stores in your JPEG file. The PyTurboJPEG does the JPEG decoding with insanely fast speed which won't do any rotation/transpose under the hood.

Unlike the PyTurboJPEG, The cv2.imread() does the post-processing to transpose your image based on the EXIF orientation tag (reference to https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/loadsave.cpp#L327).

Here I made an example to use **PyTurboJPEG** with **ExifRead** to achieve the same result like cv2.imread() did, and you need to install ExifRead upfront (e.g. pip install exifread -U)

```python
# This example shows how to use PyTurboJPEG with ExifRead to
# transpose an image if the image has an EXIF Orientation tag.
#
# pip install PyTurboJPEG -U
# pip install exifread -U

import cv2
import numpy as np
import exifread
from turbojpeg import TurboJPEG

def transposeImage(image, orientation):
    """See Orientation in https://www.exif.org/Exif2-2.PDF for details."""
    if orientation == None: return image
    val = orientation.values[0]
    if val == 1: return image
    elif val == 2: return np.fliplr(image)
    elif val == 3: return np.rot90(image, 2)
    elif val == 4: return np.flipud(image)
    elif val == 5: return np.rot90(np.flipud(image), -1)
    elif val == 6: return np.rot90(image, -1)
    elif val == 7: return np.rot90(np.flipud(image))
    elif val == 8: return np.rot90(image)

# using default library installation
turbo_jpeg = TurboJPEG()
# open jpeg file
in_file = open('foobar.jpg', 'rb')
# parse orientation
orientation = exifread.process_file(in_file).get('Image Orientation', None)
# seek file position back to 0 before decoding JPEG image
in_file.seek(0)
# start to decode the JPEG file
image = turbo_jpeg.decode(in_file.read())
# transpose image based on EXIF Orientation tag
transposed_image = transposeImage(image, orientation)
# close the file since it's no longer needed.
in_file.close()

cv2.imshow('transposed_image', transposed_image)
cv2.waitKey(0)
```

**Comment by lilohuang** [comment]
close with wontfix, user needs to apply the EXIF rotation manually. thanks.

**Comment by lfxx** [comment]
> close with wontfix, user needs to apply the EXIF rotation manually. thanks.

Thank you.If i use repo with ExifRead,would pyturbojpeg's speed been slow as opencv?

**Comment by lilohuang** [comment]
The overhead of ExifRead is negligible. PyTurboJPEG + ExifRead is still significantly FASTER than OpenCV (cv2.imread) based on my limited testing. Feel free to benchmark on your computer/server.

**Comment by lfxx** [comment]
> The overhead of ExifRead is negligible. PyTurboJPEG + ExifRead is still significantly FASTER than OpenCV (cv2.imread) based on my limited testing. Feel free to benchmark on your computer/server.

Thanks,btw,if i get the img from ```np.frombuffer(requests.get(url, stream=True, timeout=3600).content, np.uint8)```,ExifRead seems can't process this kind of data.Any suggestions?

**Comment by lilohuang** [comment]
I assume you're using Python 3 (not Python 2), here is a possible example if the JPEG file is located on web server.

```python
# This example shows how to use PyTurboJPEG with ExifRead to
# transpose an image if the image has an EXIF Orientation tag.
#
# pip install PyTurboJPEG -U
# pip install exifread -U

import cv2
import numpy as np
import exifread
import requests
from turbojpeg import TurboJPEG
from io import BytesIO

def transposeImage(image, orientation):
    """See Orientation in https://www.exif.org/Exif2-2.PDF for details."""
    if orientation == None: return image
    val = orientation.values[0]
    if val == 1: return image
    elif val == 2: return np.fliplr(image)
    elif val == 3: return np.rot90(image, 2)
    elif val == 4: return np.flipud(image)
    elif val == 5: return np.rot90(np.flipud(image), -1)
    elif val == 6: return np.rot90(image, -1)
    elif val == 7: return np.rot90(np.flipud(image))
    elif val == 8: return np.rot90(image)

# using default library installation
turbo_jpeg = TurboJPEG()
# download the jpeg file
file_content = requests.get('https://user-images.githubusercontent.com/27956643/122202251-7025a700-cecf-11eb-8f3c-f1f43a7f254f.jpg', stream=True, timeout=3600).content
# parse orientation
orientation = exifread.process_file(BytesIO(file_content)).get('Image Orientation', None)
# start to decode the JPEG file
image = turbo_jpeg.decode(file_content)
# transpose image based on EXIF Orientation tag
transposed_image = transposeImage(image, orientation)

cv2.imshow('transposed_image', transposed_image)
cv2.waitKey(0)
```

**Comment by lfxx** [comment]
> ```python
> file_content
> ```

It works!thanks.This repo is still 1x faster than opencv though added so much ops.

**Comment by lfxx** [comment]
> I assume you're using Python 3 (not Python 2), here is a possible solution if the JPEG file is located on web server.
> 
> ```python
> # This example shows how to use PyTurboJPEG with ExifRead to
> # transpose an image if the image has an EXIF Orientation tag.
> #
> # pip install PyTurboJPEG -U
> # pip install exifread -U
> 
> import cv2
> import numpy as np
> import exifread
> import requests
> from turbojpeg import TurboJPEG
> from io import BytesIO
> 
> def transposeImage(image, orientation):
>     """See Orientation in https://www.exif.org/Exif2-2.PDF for details."""
>     if orientation == None: return image
>     val = orientation.values[0]
>     if val == 1: return image
>     elif val == 2: return np.fliplr(image)
>     elif val == 3: return np.rot90(image, 2)
>     elif val == 4: return np.flipud(image)
>     elif val == 5: return np.rot90(np.flipud(image), -1)
>     elif val == 6: return np.rot90(image, -1)
>     elif val == 7: return np.rot90(np.flipud(image))
>     elif val == 8: return np.rot90(image)
> 
> # using default library installation
> turbo_jpeg = TurboJPEG()
> # download the jpeg file
> file_content = requests.get('https://user-images.githubusercontent.com/27956643/122202251-7025a700-cecf-11eb-8f3c-f1f43a7f254f.jpg', stream=True, timeout=3600).content
> # parse orientation
> orientation = exifread.process_file(BytesIO(file_content)).get('Image Orientation', None)
> # start to decode the JPEG file
> image = turbo_jpeg.decode(file_content)
> # transpose image based on EXIF Orientation tag
> transposed_image = transposeImage(image, orientation)
> 
> cv2.imshow('transposed_image', transposed_image)
> cv2.waitKey(0)
> ```

It works!thanks.This repo is still 1x faster than opencv though added so much ops.

**Comment by lfxx** [comment]
> In fact, the PyTurboJPEG (TurboJPEG API of libjpeg-turbo) does the decoding work perfectly to return the actual image (unrotated image) stores in your JPEG file. The PyTurboJPEG does the JPEG decoding with insanely fast speed which won't do any rotation/transpose under the hood.
> 
> Unlike the PyTurboJPEG, The cv2.imread() does the post-processing to transpose your image based on the EXIF orientation tag (reference to [https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/loadsave.cpp#L327](https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/loadsave.cpp?rgh-link-date=2021-06-16T12%3A35%3A29Z#L327)).
> 
> Here I made an example to use **PyTurboJPEG** with **ExifRead** to achieve the same result like cv2.imread() did, and you need to install ExifRead upfront (e.g. pip install exifread -U)
> 
> ```python
> # This example shows how to use PyTurboJPEG with ExifRead to
> # transpose an image if the image has an EXIF Orientation tag.
> #
> # pip install PyTurboJPEG -U
> # pip install exifread -U
> 
> import cv2
> import numpy as np
> import exifread
> from turbojpeg import TurboJPEG
> 
> def transposeImage(image, orientation):
>     """See Orientation in https://www.exif.org/Exif2-2.PDF for details."""
>     if orientation == None: return image
>     val = orientation.values[0]
>     if val == 1: return image
>     elif val == 2: return np.fliplr(image)
>     elif val == 3: return np.rot90(image, 2)
>     elif val == 4: return np.flipud(image)
>     elif val == 5: return np.rot90(np.flipud(image), -1)
>     elif val == 6: return np.rot90(image, -1)
>     elif val == 7: return np.rot90(np.flipud(image))
>     elif val == 8: return np.rot90(image)
> 
> # using default library installation
> turbo_jpeg = TurboJPEG()
> # open jpeg file
> in_file = open('foobar.jpg', 'rb')
> # parse orientation
> orientation = exifread.process_file(in_file).get('Image Orientation', None)
> # seek file position back to 0 before decoding JPEG image
> in_file.seek(0)
> # start to decode the JPEG file
> image = turbo_jpeg.decode(in_file.read())
> # transpose image based on EXIF Orientation tag
> transposed_image = transposeImage(image, orientation)
> # close the file since it's no longer needed.
> in_file.close()
> 
> cv2.imshow('transposed_image', transposed_image)
> cv2.waitKey(0)
> ```

The code above can deal with rotated image.But how can we save those images which are rotated?

**Comment by lilohuang** [comment]
Since numpy is **not** physically rotating the image in memory by simply changing the striding, if you want to get correct result after rotating, you need to call copy() before calling encode() function like below.

```python
out_file = open('output.jpg', 'wb')
out_file.write(turbo_jpeg.encode(transposed_image.copy()))
out_file.close()
```

**Comment by lfxx** [comment]
> Since numpy is **not** physically rotating the image in memory by simply changing the striding, if you want to get correct result after rotating, you need to call copy() before calling encode() function like below.
> 
> ```python
> out_file = open('output.jpg', 'wb')
> out_file.write(turbo_jpeg.encode(transposed_image.copy()))
> out_file.close()
> ```

This is what i need!thank you!
