### ISSUE TITLE
Multiple transform operations and modification of dct coefficents during transform

### ISSUE THREAD

**Issue by erikogabrielsson** [lilohuang/PyTurboJPEG#44]
Hi and thanks for your work,

I work with a file format converter for whole scan images (wsi), which are basically a large number of smaller images (tiles, for example 1024x1024 px) that tiled together form a large (10s of Gigapixels) image. For the conversion, I have to merge together jpeg images to a larger image (e.g. 4096x1024) and split that image into a tiles of wanted size (e.g. 4 tiles of  1024x1024). The crop function in PyTurboJPEG is very useful for this last step, however for this specific application there are 2 'issues' that could make it better:

1. tjTransform can perform multiple transform operations on the same source image ([documentation](https://cdn.rawgit.com/libjpeg-turbo/libjpeg-turbo/main/doc/html/group___turbo_j_p_e_g.html#ga9cb8abf4cc91881e04a0329b2270be25)). In PyTurboJPEG, this can be accomplished by sending arrays of pointers of the dstBufs, dstSizes, and transforms parameters. Doing multiple transforms in the same call, instead of multiple calls with single transform, improves performance by only decompressing the source image once. For my specific application, this can lead to ~50% performance boost.
2. tjTransform allows for the width and height of the crop operation to extend outside the source image. In my case, if the source image is smaller than the requested tile size it needs to be extended, and I use this feature to do so. The result is then a image where the extended part is grey (as the part is filled with dct coefficents of 0). The tjtransform struct allows a customfilter callback function to be used for modification of DCT coefficents after transformation ([documentation](https://cdn.rawgit.com/libjpeg-turbo/libjpeg-turbo/main/doc/html/structtjtransform.html)).  In order to get white (or black) background, I have therefor written a callback function that modifies the dct coefficents after transform.

I have solved these issues in a way that fits my need by sub-classing the TurboJPEG-class. If these issues something that is interesting to more users and thus something that relevant for inclusion in your library, I would be happy to work with you.

Best regards
Erik Gabrielsson

**Comment by lilohuang** [comment]
Thanks for sharing your experience on using PyTurboJPEG on your work. Since PyTurboJPEG is my holiday project, PR is welcome if it **won't** impact the existing interface (Sorry I didn't get a chance to create a bunch of unit test) 😄 

1. Performing multiple transform operations on the same source image is attractive to me especially on getting better performance.
2. Are you sending a Python function (or a callable object) as the TurboJPEG customfilter  callback? This sounds a good option to allow user change a different background color.

My reply might be slow but looking forward seeing your contribution. Thanks.

**Comment by erikogabrielsson** [comment]
Ok. We will review the code and make a merge request when it is ready and you can decide then. 

1. This is added as a separate method from the normal crop, so it shouldn't break the existing interface.
2. Yes, I use a function defined by the CUSTOMFILTER-type and provide the parameters for the background fill in the callback data.
