### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by voegtlel** [lilohuang/PyTurboJPEG#5]
Hi there,

first, thanks for quickly adding the `decode_header` function! :)

Just a small note: The arguments `pixel_format=TJPF_BGR, scaling_factor=None` seem to be unused for the `decode_header`, so I guess they could be removed?

Best
Lukas

**Comment by lilohuang** [comment]
My bad, too rush, will fix it soon. :)

**Comment by lilohuang** [comment]
Please give a try with the new version (1.1.5), and thank you for your feedback.
e.g.
pip install -U git+git://github.com/lilohuang/PyTurboJPEG.git
or
pip install -U PyTurboJPEG
