### ISSUE TITLE
Is there a way to decode only to DCT coefficients?

### ISSUE THREAD

**Issue by a-storm** [lilohuang/PyTurboJPEG#60]
I admire the rich functionality of the project, but is there really no way to read JPG into DCT coefficients?
I train forgery detecting NN and it uses several DCT features. It would be great if I can use PyTurboJPEG for image loading right into them, bypassing decoding to YUV and making DCT again.

**Comment by lilohuang** [comment]
Hi @a-storm, PyTurboJPEG is a wrapper of libjpeg-turbo (TurboJPEG API), and there is no public API to directly decode JPEG to DCT coefficients through TurboJPEG API. However, this might be done through the tjTransform function call to capture the raw DCT coefficients within the callback. Unfortunately, the implementation effort is high, I will try to investigate the possibility this year. Thanks for your feedback.

**Comment by a-storm** [comment]
Thank you for your respond! I'll try to explore tjTransform.

**Comment by xiaonengmiao** [comment]
Hi @lilohuang , according to turbo jpeg doc, there are two function: [`jpeg_read_coefficients()`](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/c23672ce52ae53bd846b555439aa0a070b6d2c07/jdtrans.c#L49)  and [`jpeg_write_coefficients()`](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/1f55ae7b0fa3acc348a630171617d0e56d922b68/jctrans.c#L43), which could read the entire image into a set of virtual coefficient-block arrays, one array per component.  The return value is a pointer to an array of virtual-array descriptors.  Each virtual array can be accessed directly using the JPEG memory manager's access_virt_barray method (see Memory management, below, and also read structure.txt's discussion of virtual array handling).  Or, for simple transcoding to a different JPEG file format, the array list can just be handed directly to jpeg_write_coefficients().

Is there any way I could call these two functions from this python wrapper? Thanks.

**Comment by xiaonengmiao** [comment]
> @xiaonengmiao, unfortunately not, because [jpeg_read_coefficients()](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/c23672ce52ae53bd846b555439aa0a070b6d2c07/jdtrans.c#L49) and [jpeg_write_coefficients()](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/1f55ae7b0fa3acc348a630171617d0e56d922b68/jctrans.c#L43), are _not_ [TurboJPEG API](https://rawcdn.githack.com/libjpeg-turbo/libjpeg-turbo/main/doc/html/group___turbo_j_p_e_g.html), they're libjpeg-turbo low-level API, you need to write C program to access them. Thanks. PyTurboJPEG only provides python wrapper of TurboJPEG API.

Understood, thanks anyway.

**Comment by nixenos** [comment]
@a-storm were you able to use the tjTransform to obtain/modify the DCT table? I wanted to hook into DCT table and replace the coefficients with ones calculated by my algorithm.

**Comment by a-storm** [comment]
@nixenos nope. I calculated them with scipy. share it please if you succeed.

**Comment by nixenos** [comment]
@lilohuang is calling tjTransform for replacing DCT coefficients supported by this library? 
@a-storm sure, I'm planning to try it anyways, if it won't work I might need to switch my project to C++, which would be very unfortunate as I'm on a tight time schedule (it's for my masters thesis and I need to get it working soon hehe)
