### ISSUE TITLE
Do not raise decoder warnings

### ISSUE THREAD

**Issue by voegtlel** [lilohuang/PyTurboJPEG#7]
Hey there,

I have another request: Some specific images yield warnings, which are currently handled as exceptions (see https://github.com/libjpeg-turbo/libjpeg-turbo/issues/157#issuecomment-321011697 ).
For fixing that, I suggest the following:
Add `tjGetErrorCode` to the imports:
```py
        self.__get_error_code = turbo_jpeg.tjGetErrorCode
        self.__get_error_code.argtypes = [
            c_void_p
        ]
        self.__get_error_code.restype = c_int
```
instead of immediately raising the `IOError` exception if the `status` is not 0, use that function to check if it's a warning:
```py
import warnings
[...]
            err_code = self.__get_error_code(handle)
            if status != 0:
                if err_code == 0:
                    warnings.warn(self.__get_error_str().decode())
                else:
                    raise IOError(self.__get_error_str().decode(), err_code)
```

(unfortunately, I'm limited in what code I can commit as PR, so writing that stuff here, so you can do that)

Thanks!

**Comment by lilohuang** [comment]
Thank you for your suggestion. I will try to improve it this weekend. Please stay tuned.

**Comment by voegtlel** [comment]
Thank you!
