### ISSUE TITLE
Default library paths

### ISSUE THREAD

**Issue by voegtlel** [lilohuang/PyTurboJPEG#8]
Hey there,

still one more hint: I believe it's a cleaner interface if you'd use `from ctypes.util import find_library` like `find_library("turbojpeg")` to detect the path to the library instead of the hardcoded dictionary :) (I'm doing exactly that and pass the result to the constructor).

Thanks!

**Comment by lilohuang** [comment]
May I know which operating system you are testing? How you install the turbojpeg library? Somehow calling find_library() doesn't work well on my Mac OS X and CentOS server. I can consider to call this find_library() in priority, and then using the hardcoded path if find_library() returning invalid path.

**Comment by voegtlel** [comment]
Thanks for your response!
I'm testing on Windows and Linux (Ubuntu). On Windows, the dll must be in the PATH variable, and on Ubuntu it suffices to install the system library.
Didn't expect that this doesn't work on other OSes.
